name: ocean-research
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - pandas
  - statsmodels
  - seaborn
  - sympy
  - cython
  - xarray
  - dask
  - netCDF4
  - pint
  - pint-xarray
  - gsw
  - gsw-xarray
  - cftime
  - cartopy
